#!/bin/bash

set -euo pipefail

INTERPRETER_PATH=$(realpath "$0" | xargs dirname)

FAT_JAR="$INTERPRETER_PATH/build/libs/tkom-1.0-SNAPSHOT-all.jar"
FILE="$INTERPRETER_PATH/src/main/resources/query.txt"

help () {
    cat 1>&2 << EOF
Usage: $0 [OPTION] [FILE]
    -h --help        Display this message
    -c --clean       Re-build project from scratch before running application
EOF
exit 0;
}

while [[ $# -gt 0 ]]; do
  case $1 in
    -h|--help)
        help
        ;;
    -c|--clean)
        ./gradlew clean 1>&2
        shift
        ;;
    -*)
        echo "Unknown option $1" 1>&2
        help
        exit 1
        ;;
    *)
        FILE="$1"
        shift
        ;;
  esac
done



if [ ! -f "$FAT_JAR" ]; then
  exec "$INTERPRETER_PATH/gradlew" shadowJar 1>&2
fi

java -jar "$FAT_JAR" "$FILE"
