package org.example.ast;

public enum ExpressionType {
	PROGRAM,
	FUNCTION_DECLARATION,
	DECLARATION,
	STATEMENT_BLOCK,
	WHILE_STATEMENT,
	RETURN_STATEMENT,
	EXPRESSION,
	INIT_STATEMENT,
	ASSIGN_STATEMENT,
	FUNCTION_CALL,
	VARIABLE,
	CONDITION,
	INTEGER_VALUE,
	FLOATING_POINT_VALUE,
	STRING,
	IF_STATEMENT,
	BOOLEAN,
	PRINT,
	END_OF_FILE
}
